### PR TITLE
Update db.ccp to add instruments to randomizer

### PR DESCRIPTION
**Pull request by TehDreadPirateRoberts**
Add instruments to the randomizer.

### CODE REVIEW

**Comment by mcinelli61** [comment]
Who decided that this is what we wanted to do?

**Comment by TehDreadPirateRoberts** [comment]
> Who decided that this is what we wanted to do?
> […](#)

Well it sure seemed like another thing missed during some of the coding. If people read and replied to the shit I posted on the forums I might be more inclined to seek consensus.

**Comment by TehDreadPirateRoberts** [comment]
> Who decided that this is what we wanted to do?
> […](#)

And I posted it for review. You can still go ahead and not approve it.

**Comment by TehDreadPirateRoberts** [comment]
I have posted it to the forums for discussion.

**Comment by dmhenderson76** [comment]
I think we should do a review of what should *not* be randomized and not just add items piecemeal.  There are some spells and effects that should not be randomized (heal, vamp touch, dispel magic etc) but most things should - including skill bonuses - especially as we move towards EQ that benefits different classes in different ways

**Comment by TehDreadPirateRoberts** [comment]
> I think we should do a review of what should _not_ be randomized and not just add items piecemeal. There are some spells and effects that should not be randomized (heal, vamp touch, dispel magic etc) but most things should - including skill bonuses - especially as we move towards EQ that benefits different classes in different ways

I posted to forums details regarding affects for discussion. Skill bonus may be more challenging to randomize. I don't know though.

**Review by jhhudso — APPROVED** [review]

**Pull request merged**
